stages:
  - prep
  - build
  - test



# Ubuntu 16
# EOL: 04/01/2021
#build-kali-x86_64:
#  stage: build
#  before_script:
#    - mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
#    - rm -rf ~/rpmbuild/BUILD/* || true
#    - cp *.spec ~/rpmbuild/SPECS/
#    - rm -rf ~/rpmbuild/SOURCES/*
#    - cp SOURCES/* ~/rpmbuild/SOURCES/
#    - cd src/ && tar zcvf ~/rpmbuild/SOURCES/gvm-20.8.0.tar.gz gvm-20.8.0/ && cd ..
#    - git clone https://gitlab.dev.atomicorp.com/atomicrocketturtle/buildsys-tools
#    - cp buildsys-tools/* ~/bin/
#    - chmod +x ~/bin/build-debian.sh
#
#  script:
#    -  (if [[ $CI_BUILD_REF_NAME == "master" ]]; then  dist=kali arch=amd64 ~/bin/build-debian.sh -b gvm.spec /mnt/repo/atomic-testing/debian/; else  dist=kali arch=amd64 ~/bin/build-debian.sh -b gvm.spec /mnt/repo/atomic-bleeding/debian/; fi )



#build-el7-x86_64:
#  stage: build
#  before_script:
#    - mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
#    - mkdir -p ~/mock
#    - cp mock/* ~/mock/
#    - cp *.spec ~/rpmbuild/SPECS/
#    - cp SOURCES/* ~/rpmbuild/SOURCES/
#    - cd src/ && tar zcvf ~/rpmbuild/SOURCES/gvm-20.8.0.tar.gz gvm-20.8.0/ && cd ..
#    
#
#  script:
#    - (if [[ $CI_BUILD_REF_NAME == "master" ]]; then  gitlab-build.sh el7-x86_64 gvm.spec /mnt/repo/atomic-testing/centos/7/x86_64/ ; else  gitlab-build.sh el7-x86_64 gvm.spec /mnt/repo/atomic-bleeding/centos/7/x86_64/ ; fi )
#

build-el9-x86_64:
  stage: prep
  before_script:
    - mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
    - mkdir -p ~/mock
    - cp mock/* ~/mock/
    - cp *.spec ~/rpmbuild/SPECS/
    - cp SOURCES/* ~/rpmbuild/SOURCES/
    - cd src/ && tar zcvf ~/rpmbuild/SOURCES/gvm.tar.gz gvm/ && cd ..


  script:
    - (if [[ $CI_BUILD_REF_NAME == "master" ]]; then  gitlab-build.sh el9-x86_64 gvm.spec /mnt/repo/atomic-testing/rocky/9/x86_64/ ; else  gitlab-build.sh el9-x86_64 gvm.spec /mnt/repo/atomic-bleeding/rocky/9/x86_64/ ; fi )


build-el8-x86_64:
  stage: build
  before_script:
    - mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
    - mkdir -p ~/mock
    - cp mock/* ~/mock/
    - cp *.spec ~/rpmbuild/SPECS/
    - cp SOURCES/* ~/rpmbuild/SOURCES/
    - cd src/ && tar zcvf ~/rpmbuild/SOURCES/gvm.tar.gz gvm/ && cd ..


  script:
    - (if [[ $CI_BUILD_REF_NAME == "master" ]]; then  gitlab-build.sh el8-x86_64 gvm.spec /mnt/repo/atomic-testing/centos/8/x86_64/ ; else  gitlab-build.sh el8-x86_64 gvm.spec /mnt/repo/atomic-bleeding/centos/8/x86_64/ ; fi )

#build-fc32-x86_64:
#  stage: build
#  before_script:
#    - mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
#    - mkdir -p ~/mock
#    - cp mock/* ~/mock/
#    - cp gvm.spec ~/rpmbuild/SPECS/
#    - cp SOURCES/* ~/rpmbuild/SOURCES/
#    - cd src/ && tar zcvf ~/rpmbuild/SOURCES/gvm-20.8.0.tar.gz gvm-20.8.0/ && cd ..
#
#
#  script:
#    - (if [[ $CI_BUILD_REF_NAME == "master" ]]; then  gitlab-build.sh fc32-x86_64 gvm.spec /mnt/repo/atomic-testing/fedora/32/x86_64 ; else  gitlab-build.sh fc32-x86_64 gvm.spec /mnt/repo/atomic-bleeding/fedora/32/x86_64 ; fi )
#


build-fc35-x86_64:
  stage: build
  before_script:
    - mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
    - mkdir -p ~/mock
    - cp mock/* ~/mock/
    - cp gvm.spec ~/rpmbuild/SPECS/
    - cp SOURCES/* ~/rpmbuild/SOURCES/
    - cd src/ && tar zcvf ~/rpmbuild/SOURCES/gvm.tar.gz gvm/ && cd ..


  script:
    - (if [[ $CI_BUILD_REF_NAME == "master" ]]; then  gitlab-build.sh fc35-x86_64 gvm.spec /mnt/repo/atomic-testing/fedora/35/x86_64 ; else  gitlab-build.sh fc35-x86_64 gvm.spec /mnt/repo/atomic-bleeding/fedora/35/x86_64 ; fi )

build-fc36-x86_64:
  stage: build
  before_script:
    - mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
    - mkdir -p ~/mock
    - cp mock/* ~/mock/
    - cp gvm.spec ~/rpmbuild/SPECS/
    - cp SOURCES/* ~/rpmbuild/SOURCES/
    - cd src/ && tar zcvf ~/rpmbuild/SOURCES/gvm.tar.gz gvm/ && cd ..


  script:
    - (if [[ $CI_BUILD_REF_NAME == "master" ]]; then  gitlab-build.sh fc36-x86_64 gvm.spec /mnt/repo/atomic-testing/fedora/36/x86_64 ; else  gitlab-build.sh fc36-x86_64 gvm.spec /mnt/repo/atomic-bleeding/fedora/36/x86_64 ; fi )

build-fc37-x86_64:
  stage: build
  before_script:
    - mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
    - mkdir -p ~/mock
    - cp mock/* ~/mock/
    - cp gvm.spec ~/rpmbuild/SPECS/
    - cp SOURCES/* ~/rpmbuild/SOURCES/
    - cd src/ && tar zcvf ~/rpmbuild/SOURCES/gvm.tar.gz gvm/ && cd ..


  script:
    - (if [[ $CI_BUILD_REF_NAME == "master" ]]; then  gitlab-build.sh fc37-x86_64 gvm.spec /mnt/repo/atomic-testing/fedora/37/x86_64 ; else  gitlab-build.sh fc37-x86_64 gvm.spec /mnt/repo/atomic-bleeding/fedora/37/x86_64 ; fi )




#test-el7-x86_65:
#  stage: test
#  script: 
#    #- cd tests && docker build --build-arg HTTP_PROXY=http://10.66.6.1:3128 --build-arg http_proxy=http://10.66.6.1:3128  --build-arg RSYNC_PROXY=10.66.6.1:3128 .
#    - cd tests && docker build  .


